name: Build and Deploy Spring Boot API to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build with Maven
        run: |
          mvn clean package -DskipTests

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: advancedswe.azurecr.io
          username: ${{ secrets.AZURE_ACR_USERNAME }}
          password: ${{ secrets.AZURE_ACR_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t advancedswe.azurecr.io/chatgpt:v1 .
          docker push advancedswe.azurecr.io/chatgpt:v1

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Container Instance
        run: |
          az container create \
            --resource-group Advanced-SWE_group \
            --name springboot-api-instance \
            --image advancedswe.azurecr.io/chatgpt:v1 \
            --cpu 1 \
            --memory 1 \
            --registry-login-server advancedswe.azurecr.io \
            --dns-name-label springboot-api \
            --ports 8080 \
            --registry-username ${{ secrets.AZURE_ACR_USERNAME }} \
            --registry-password ${{ secrets.AZURE_ACR_PASSWORD }} \
            --restart-policy Always
