name: Build and Deploy Spring Boot API to Azure VM with Systemd

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build with Maven
        run: |
          mvn clean package -DskipTests

      - name: Deploy to Azure VM
        run: |
          echo "${{ secrets.VM_SSH_KEY }}" > azure_key.pem
          chmod 600 azure_key.pem
          
          ssh -i azure_key.pem -o StrictHostKeyChecking=no -p ${{ secrets.VM_PORT }} ${{ secrets.VM_USERNAME }}@${{ secrets.VM_HOST }} <<EOF
            sudo mkdir -p /opt/chatgpt/
            sudo chmod -R 777 /opt/chatgpt/
            sudo rm -rf /opt/chatgpt/*
          EOF
          
          scp -i azure_key.pem -P ${{ secrets.VM_PORT }} target/MS-ChatGPT-0.0.1-SNAPSHOT.jar ${{ secrets.VM_USERNAME }}@${{ secrets.VM_HOST }}:/opt/chatgpt/

          ssh -i azure_key.pem -o StrictHostKeyChecking=no -p ${{ secrets.VM_PORT }} ${{ secrets.VM_USERNAME }}@${{ secrets.VM_HOST }} <<EOF
            sudo systemctl restart your-spring-boot-service  # Adjust as needed
          EOF

      - name: Clean up
        run: rm -f azure_key.pem
