services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb-chatgpt
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: root
    volumes:
      - ./data:/data/db
      - ./docker/mariadb/init.sql:/docker-entrypoint-initdb.d/init.sql
