name: Deploy Angular App to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Dependencies
      run: npm install

    - name: Build Angular App
      run: npm run build -- --configuration production

    - name: Verify Build Output
      run: |
        ls -l dist/
        ls -l dist/personal-digital-agent-frontend/

    - name: Deploy to Azure Server
      run: |
        ssh -i ~/.ssh/private_key.pem -o StrictHostKeyChecking=no ${{ secrets.AZURE_SSH_USER }}@${{ secrets.AZURE_SERVER_IP }} <<EOF
          sudo rm -rf /var/www/html/*
          sudo mkdir -p /tmp/deployment
        EOF
        scp -i ~/.ssh/private_key.pem -r dist/personal-digital-agent-frontend/* ${{ secrets.AZURE_SSH_USER }}@${{ secrets.AZURE_SERVER_IP }}:/tmp/deployment
        ssh -i ~/.ssh/private_key.pem -o StrictHostKeyChecking=no ${{ secrets.AZURE_SSH_USER }}@${{ secrets.AZURE_SERVER_IP }} <<EOF
          sudo mv /tmp/deployment/* /var/www/html/
          sudo chown -R www-data:www-data /var/www/html/
          sudo chmod -R 755 /var/www/html/
          sudo systemctl restart apache2
        EOF
