name: Deploy Angular App to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Dependencies
      run: npm install

    - name: Build Angular App
      run: npm run build -- --configuration production

    - name: Verify Build Output
      run: ls -l dist/

    - name: Copy Files to Azure Server
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.AZURE_SERVER_IP }}
        username: ${{ secrets.AZURE_SSH_USER }}
        key: ${{ secrets.AZURE_SSH_PRIVATE_KEY }}
        source: "dist/personal-digital-agent-frontend/*"
        target: "/var/www/html/"

    - name: Restart Apache on Azure Server
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.AZURE_SERVER_IP }}
        username: ${{ secrets.AZURE_SSH_USER }}
        key: ${{ secrets.AZURE_SSH_PRIVATE_KEY }}
        port: 22
        script: |
          sudo systemctl restart apache2
